// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DbIcon: typeof import('../../../packages/components/icon/index')['default']
    DbTest: typeof import('./../components/DbTest/index.vue')['default']
  }
}
