// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Component: typeof import('./../components/layout/component/index.vue')['default']
    Con: typeof import('./../components/Con/index.vue')['default']
    DbIcon: typeof import('../../../packages/components/icon/index')['default']
    DbTest: typeof import('./../components/DbTest/index.vue')['default']
    Layout: typeof import('./../components/layout/index.vue')['default']
    Layout2: typeof import('./../components/layout2/index.vue')['default']
    Provider: typeof import('./../components/provider/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
